name: Android CI (Java + C++)

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # نیاز به gradle wrapper نداریم؛ از اکشن رسمی گریدل استفاده می‌کنیم
      - name: Setup Gradle 8.7
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7

      - name: Build Debug APK
        run: gradle :app:assembleDebug --no-daemon

      - name: Upload APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
